user-ip endpoint
Program-AR/pilas-bloques-api pull request #20
Opened 2022-10-25 12:28 UTC by ezequielPereyra

Related to: https://github.com/Program-AR/pilas-bloques/issues/1158

pilas-bloques: https://github.com/Program-AR/pilas-bloques/pull/1164

2022-10-25 13:42 UTC, ezequielPereyra commented
Docu de express (parece más directo): https://expressjs.com/en/api.html#req.ip

La ip puede venir con caracteres al principio: https://stackoverflow.com/questions/31100703/stripping-ffff-prefix-from-request-connection-remoteaddress-nodejs

Relacionados: https://stackoverflow.com/questions/8107856/how-to-determine-a-users-ip-address-in-node, https://stackoverflow.com/questions/24896386/request-connection-remoteaddress-now-prefixed-in-ffff-in-node-js

2022-10-26 14:42 UTC, asanzo approved these changes
Te estaba por bardear por meter guiones en el nombre del endpoint pero [tenés razón](https://restfulapi.net/resource-naming/)

2022-10-26 14:48 UTC, asanzo requested changes
Perdón, reculé. Hay un caso que hay que considerar.

2022-10-26 14:48 UTC, asanzo commented on src/routes/ip.ts
> +    const response = await fetch("https://api64.ipify.org?format=json")
Perate, acá tenemos que considerar el error. Tengo miedo de que ipify nos banee por gedes, ahora que van a llegar todos los pedidos desde el mismo servidor (el nuestro).
Deberíamos enterarnos (y pronto) si la estamos cagando. No sé si no mandar un mail a desarrollo-programar en el caso de error (además de loguear, por supuesto). 

Puede ser mucho un mail por error, creo...

2022-10-26 16:28 UTC, ezequielPereyra commented on src/routes/ip.ts
> +    const response = await fetch("https://api64.ipify.org?format=json")
Podemos ir por esta falopeada https://stackoverflow.com/questions/31100703/stripping-ffff-prefix-from-request-connection-remoteaddress-nodejs e ir probando. Agregando `request.ip`, tenemos un proxy nosotros? Porque si es así hay que cambiar una configuración https://expressjs.com/en/4x/api.html#trust.proxy.options.table. Lo malo es que si tenemos proxy saca la ip del header `X-Forwarded-*` y en la misma documentación dice que eso es fácil de spoofear y además no es de confiar (https://expressjs.com/en/4x/api.html#app.settings.table en la parte de `trust proxy`).

Cuando yo hice la prueba me vino una ipv6 pero formateada a partir de mi ipv4 (le agrega algunos caracteres al principio). Si llegan ipv6 formateadas a partir de ipv4 estamos bien porque cumple con lo que necesitamos. Pero si llegan ipv6 ahi no sé, creo que no se comparten aunque se conecten con el mismo router. Igual mi conocimiento sobre esto es nulo, capaz hablo boludeces.

2022-10-28 15:24 UTC, asanzo commented on src/routes/ip.ts
> +    const response = await fetch("https://api64.ipify.org?format=json")
@ezequielPereyra Según la [config](https://github.com/fundacion-sadosky/containerization/blob/9104566a4782b5c4260fe903939f7837db929b0d/frontend/etc/nginx/primarias/sdky-pilasbloques.conf#L14) del server, estamos haciendo esos reenvíos de header.
Probemos por el lado de trust proxy.
Y no sé qué onda el formato de la ip

2022-10-28 17:52 UTC, asanzo approved these changes
:+1: 
Genial!! Hice un comment pavo. 
@ezequielPereyra te animás a mergear, releasear y deployar a staging? Luego de hacer un par de pruebas ahí podemos deployar a prod tmb y testear en caliente :smiling_imp:

2022-10-28 17:52 UTC, asanzo commented on src/routes/ip.ts
> +    res.json(jsonIp)
```suggestion
    res.json({ ip: req.ip })
```

2022-10-28 17:59 UTC, merged